import React from 'react';
import { createRoot } from 'react-dom/client';
import '../styles/foundation/tokens.css';
import '../styles/foundation/base.css';
import '../styles/foundation/shell.css';
import '../styles/components/primitives.css';
import '../styles/components/secondary.css';
import '../styles/components/mbti-survey.css';
import '../styles/components/insights.css';
import '../styles/foundation/motion.css';
import '../styles/components/modals.css';
import '../styles/components/navigation.css';
import '../styles/components/sheets.css';
import '../styles/components/drawers.css';
import '../styles/screens/auth-signup.css';
import '../styles/screens/auth-recovery.css';
import '../styles/screens/auth.css';
import '../styles/screens/onboarding.css';
import '../styles/screens/locked-splash.css';
import '../styles/screens/home-overlays.css';
import '../styles/screens/home-base.css';
import '../styles/screens/home.css';
import '../styles/screens/analysis-base.css';
import '../styles/screens/analysis-unified.css';
import '../styles/screens/analysis.css';
import '../styles/screens/planner-calendar.css';
import '../styles/screens/planner.css';
import '../styles/screens/planner-add.css';
import '../styles/screens/coaching.css';
import '../styles/screens/reports.css';
import '../styles/screens/service.css';
import '../styles/screens/mypage-support.css';
import '../styles/screens/mypage-data.css';
import '../styles/screens/mypage.css';
import '../styles/screens/ranking.css';
import '../styles/screens/score-input.css';
import '../styles/layout/mobile-layout-system.css';
import MobileApp from '../app/MobileApp.js';
import { CRACKY_SRC, ONBOARDING_LOGO_SRC } from '../constants/assets.js';
import { getMobileRootElement, markMobileAppBooted } from '../shared/browser/mobile-runtime.js';

markMobileAppBooted({ crackySrc: CRACKY_SRC, onboardingLogoSrc: ONBOARDING_LOGO_SRC });

const rootElement = getMobileRootElement();
if (rootElement) createRoot(rootElement).render(React.createElement(MobileApp));
