import React from 'react';
import { listCounselorWrittenSessions } from '../written-session-api.js';
import { approveAdminReport, downloadConsultingReport, getAdminReportReview, getCounselorReportDraft, getStudentConsultingReport, saveCounselorReportDraft, submitCounselorReportReview } from '../report-api.js';
import { CONSULTING_ROUTES, navigateConsulting } from '../route-model.js';

const blankCandidate = () => ({ universityName: '', admissionUnitName: '', admissionGroup: '', riskBand: 'manual_review', rationale: '' });
const blankContent = () => ({ title: '2027 정시 지원 전략 보고서', executiveSummary: '', scoreAssessment: '', candidates: [blankCandidate()], applicationStrategy: '', risksAndCautions: '', finalCallChecklist: '' });

function CandidateCards({ candidates }) {
  const probability = candidate => candidate.probability && typeof candidate.probability === 'object' ? `${candidate.probability.low ?? '?'}~${candidate.probability.high ?? '?'}%` : candidate.probability ?? '확률 확인 중';
  return <div className="consulting-report-candidates">{candidates.map((candidate, index) => <article key={candidate.candidateId || `${candidate.universityName}-${index}`}><span>{candidate.admissionGroup || '모집군 확인'}</span><h3>{candidate.universityName} {candidate.admissionUnitName}</h3><p>{candidate.rationale}</p><small>{candidate.probabilityStatus === 'manual_review' ? '상담사 수동 검토 · 확률 미제공' : `${candidate.riskBand} · ${probability(candidate)}`}</small></article>)}</div>;
}

function StudentReport({ binding }) {
  const [state, setState] = React.useState({ status: 'loading', report: null, error: '' });
  const [pdfBusy, setPdfBusy] = React.useState(false);
  React.useEffect(() => { const controller = new AbortController(); getStudentConsultingReport(binding, controller.signal).then(result => { if (!controller.signal.aborted) setState(result.ok ? { status: 'ready', report: result.data.report, error: '' } : { status: 'error', report: null, error: result.error }); }); return () => controller.abort(); }, [binding]);
  const pdf = async () => { setPdfBusy(true); const result = await downloadConsultingReport(binding, state.report.reportId); if (result.ok) globalThis.location.assign(result.downloadUrl); else setState(value => ({ ...value, error: result.error })); setPdfBusy(false); };
  if (state.status === 'loading') return <main className="consulting-v2-center"><p className="consulting-v2-loading">보고서를 불러오고 있습니다.</p></main>;
  if (state.status === 'error' || !state.report) return <main className="consulting-v2-center"><section className="consulting-v2-card"><h1>{state.status === 'error' ? '보고서를 불러오지 못했습니다' : '보고서를 준비하고 있습니다'}</h1><p className="consulting-v2-status">{state.error || '승인과 공개가 완료되면 이곳에서 확인할 수 있습니다.'}</p><button className="consulting-v2-secondary consulting-v2-wide" onClick={() => navigateConsulting(CONSULTING_ROUTES.home)}>진행 현황으로 돌아가기</button></section></main>;
  const { content } = state.report;
  return <main className="consulting-report"><header><button type="button" onClick={() => navigateConsulting(CONSULTING_ROUTES.home)}>← 진행 현황</button><strong>정시 컨설팅 보고서</strong><button type="button" disabled={pdfBusy} onClick={pdf}>{pdfBusy ? 'PDF 생성 중…' : 'PDF 받기'}</button></header><article className="consulting-report-document"><p className="consulting-v2-kicker">STUDYCRACK · 2027 JUNGSI</p><h1>{content.title}</h1><time>{new Intl.DateTimeFormat('ko-KR', { dateStyle: 'long' }).format(new Date(state.report.publishedAt))} 공개</time><section><h2>핵심 요약</h2><p>{content.executiveSummary}</p></section><section><h2>성적 판단</h2><p>{content.scoreAssessment}</p></section><section><h2>지원 후보</h2><CandidateCards candidates={content.candidates} /></section><section><h2>지원 전략</h2><p>{content.applicationStrategy}</p></section><section><h2>위험 요소와 유의사항</h2><p>{content.risksAndCautions}</p></section><section><h2>파이널 콜 확인 항목</h2><p>{content.finalCallChecklist}</p></section><button className="consulting-v2-primary consulting-v2-wide" type="button" onClick={() => navigateConsulting(CONSULTING_ROUTES.finalCall)}>파이널 콜 일정 선택하기</button>{state.error ? <p role="status">{state.error}</p> : null}</article></main>;
}

function ReportForm({ binding, caseId, initial, transcriptHash, workflowState }) {
  const [content, setContent] = React.useState(initial?.content || blankContent());
  const [draftRevision, setDraftRevision] = React.useState(Number(initial?.draftRevision || 0));
  const [fallback, setFallback] = React.useState(initial?.analysisFallback || { status: 'manual_review', reason: '후보 추천 엔진 도입 전 상담사 수동 검토 결과' });
  const [feedback, setFeedback] = React.useState('');
  const [busy, setBusy] = React.useState(false);
  const [submitted, setSubmitted] = React.useState(false);
  const [autosaveRevision, setAutosaveRevision] = React.useState(0);
  const savedAutosaveRevision = React.useRef(0);
  const editable = !submitted && !['review', 'approved'].includes(initial?.status) && !['REPORT_REVIEW', 'REPORT_SCHEDULED', 'FINAL_CALL_SCHEDULING'].includes(workflowState);
  const complete = [content.title, content.executiveSummary, content.scoreAssessment, content.applicationStrategy, content.risksAndCautions, content.finalCallChecklist, fallback.reason].every(value => String(value || '').trim()) && content.candidates.every(item => [item.universityName, item.admissionUnitName, item.admissionGroup, item.rationale].every(value => String(value || '').trim()));
  const touch = () => setAutosaveRevision(value => value + 1);
  const field = (key, value) => { setContent(current => ({ ...current, [key]: value })); touch(); };
  const candidate = (index, key, value) => { setContent(current => ({ ...current, candidates: current.candidates.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) })); touch(); };
  const save = async (sourceRevision = autosaveRevision) => { setBusy(true); setFeedback(''); const result = await saveCounselorReportDraft(binding, { caseId, expectedDraftRevision: draftRevision, transcriptHash, analysisFallback: fallback, content }); if (result.ok) { savedAutosaveRevision.current = Math.max(savedAutosaveRevision.current, sourceRevision); setDraftRevision(result.data.draftRevision); setFeedback('초안을 저장했습니다.'); } else setFeedback(result.error); setBusy(false); return result.ok; };
  const submit = async () => { if (!await save()) return; const result = await submitCounselorReportReview(binding, caseId); if (result.ok) setSubmitted(true); setFeedback(result.ok ? '관리자 검수를 요청했습니다.' : result.error); };
  React.useEffect(() => { if (!editable || autosaveRevision === 0 || busy || savedAutosaveRevision.current === autosaveRevision) return undefined; const timer = setTimeout(() => { save(autosaveRevision); }, 1500); return () => clearTimeout(timer); }, [autosaveRevision, busy]);
  return <section className="consulting-report-workbench"><div className="consulting-report-workbench-head"><div><p className="consulting-v2-kicker">상담사 전용</p><h1>보고서 작성</h1></div><span>{initial?.status === 'review' ? '검수 중' : initial?.status === 'approved' ? '승인 완료' : `초안 v${draftRevision}`}</span></div><fieldset disabled={!editable || busy}><label>제목<input maxLength="120" value={content.title} onChange={event => field('title', event.target.value)} /></label><label>핵심 요약<textarea maxLength="3000" value={content.executiveSummary} onChange={event => field('executiveSummary', event.target.value)} /></label><label>성적 판단<textarea maxLength="4000" value={content.scoreAssessment} onChange={event => field('scoreAssessment', event.target.value)} /></label><div className="consulting-report-editor-candidates"><h2>지원 후보</h2>{content.candidates.map((item, index) => <article key={index}><div><input aria-label={`후보 ${index + 1} 대학`} placeholder="대학" maxLength="120" value={item.universityName} onChange={event => candidate(index, 'universityName', event.target.value)} /><input aria-label={`후보 ${index + 1} 모집단위`} placeholder="모집단위" maxLength="120" value={item.admissionUnitName} onChange={event => candidate(index, 'admissionUnitName', event.target.value)} /><input aria-label={`후보 ${index + 1} 모집군`} placeholder="가/나/다군" maxLength="20" value={item.admissionGroup} onChange={event => candidate(index, 'admissionGroup', event.target.value)} /></div><textarea aria-label={`후보 ${index + 1} 근거`} placeholder="추천 근거" maxLength="1000" value={item.rationale} onChange={event => candidate(index, 'rationale', event.target.value)} /></article>)}<div className="consulting-report-row-actions"><button type="button" disabled={content.candidates.length >= 10} onClick={() => field('candidates', [...content.candidates, blankCandidate()])}>후보 추가</button><button type="button" disabled={content.candidates.length <= 1} onClick={() => field('candidates', content.candidates.slice(0, -1))}>마지막 후보 삭제</button></div></div><label>지원 전략<textarea maxLength="5000" value={content.applicationStrategy} onChange={event => field('applicationStrategy', event.target.value)} /></label><label>위험 요소와 유의사항<textarea maxLength="3000" value={content.risksAndCautions} onChange={event => field('risksAndCautions', event.target.value)} /></label><label>파이널 콜 확인 항목<textarea maxLength="2000" value={content.finalCallChecklist} onChange={event => field('finalCallChecklist', event.target.value)} /></label><label>수동 검토 사유<textarea maxLength="1000" value={fallback.reason} onChange={event => { setFallback(current => ({ ...current, reason: event.target.value })); touch(); }} /></label></fieldset>{editable ? <div className="consulting-report-actions"><button type="button" disabled={busy} onClick={save}>초안 저장</button><button type="button" disabled={busy || !complete} onClick={submit}>저장 후 검수 요청</button></div> : null}{feedback ? <p role="status">{feedback}</p> : null}</section>;
}

function CounselorReport({ binding }) {
  const queryCaseId = new URLSearchParams(globalThis.location?.search || '').get('caseId') || '';
  const [state, setState] = React.useState({ status: 'loading', caseId: queryCaseId, sessions: [], data: null, error: '' });
  React.useEffect(() => { const controller = new AbortController(); (async () => { const listed = await listCounselorWrittenSessions(binding, controller.signal); if (!listed.ok) return setState(value => ({ ...value, status: 'error', error: listed.error })); const completed = (listed.data.sessions || []).filter(item => item.status === 'completed'); const caseId = state.caseId || completed[0]?.caseId || ''; if (!caseId) return setState({ status: 'error', caseId: '', sessions: completed, data: null, error: '완료된 서면상담이 없습니다.' }); const loaded = await getCounselorReportDraft(binding, caseId, controller.signal); if (!controller.signal.aborted) setState({ status: loaded.ok ? 'ready' : 'error', caseId, sessions: completed, data: loaded.data || null, error: loaded.error || '' }); })(); return () => controller.abort(); }, [binding, state.caseId]);
  if (state.status !== 'ready') return <main className="consulting-v2-center"><section className="consulting-v2-card"><h1>{state.status === 'loading' ? '보고서를 불러오고 있습니다' : '보고서를 열 수 없습니다'}</h1><p className="consulting-v2-status">{state.error}</p></section></main>;
  return <main className="consulting-report"><header><button type="button" onClick={() => globalThis.location.assign('/mypage/tutor')}>← 상담사 페이지</button><strong>정시 컨설팅 보고서</strong><select aria-label="학생 케이스 선택" value={state.caseId} onChange={event => setState(value => ({ ...value, status: 'loading', caseId: event.target.value }))}>{state.sessions.map(item => <option key={item.caseId} value={item.caseId}>{item.caseId.slice(-8)}</option>)}</select></header><ReportForm key={`${state.caseId}-${state.data.draft?.draftRevision || 0}`} binding={binding} caseId={state.caseId} initial={state.data.draft} transcriptHash={state.data.transcriptHash} workflowState={state.data.workflowState} /></main>;
}

function AdminReport({ binding }) {
  const caseId = new URLSearchParams(globalThis.location?.search || '').get('caseId') || '';
  const [state, setState] = React.useState({ status: 'loading', data: null, error: '' });
  const [releaseAt, setReleaseAt] = React.useState('');
  const [approved, setApproved] = React.useState(false);
  React.useEffect(() => { const controller = new AbortController(); if (!caseId) { setState({ status: 'error', data: null, error: 'caseId가 필요합니다.' }); return () => {}; } getAdminReportReview(binding, caseId, controller.signal).then(result => { if (!controller.signal.aborted) setState(result.ok ? { status: 'ready', data: result.data, error: '' } : { status: 'error', data: null, error: result.error }); }); return () => controller.abort(); }, [binding, caseId]);
  const approve = async () => { const iso = new Date(releaseAt).toISOString(); const result = await approveAdminReport(binding, { caseId, releaseAt: iso }); if (result.ok) setApproved(true); setState(value => ({ ...value, error: result.ok ? `승인 완료 · ${new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(result.data.releaseAt))} 공개 예정` : result.error })); };
  if (state.status !== 'ready') return <main className="consulting-v2-center"><section className="consulting-v2-card"><h1>보고서 검수</h1><p className="consulting-v2-status">{state.error || '불러오는 중입니다.'}</p></section></main>;
  const content = state.data.draft?.content;
  if (!content) return <main className="consulting-v2-center"><section className="consulting-v2-card"><h1>검수할 보고서가 없습니다</h1><p className="consulting-v2-status">상담사가 검수를 요청한 뒤 다시 확인해주세요.</p></section></main>;
  return <main className="consulting-report"><header><button type="button" onClick={() => globalThis.location.assign('/admin_index.html')}>← 관리자</button><strong>보고서 승인</strong><span>{approved ? '승인 완료' : state.data.workflowState}</span></header><article className="consulting-report-document"><h1>{content.title}</h1><section><h2>핵심 요약</h2><p>{content.executiveSummary}</p></section><section><h2>성적 판단</h2><p>{content.scoreAssessment}</p></section><CandidateCards candidates={content.candidates} /><section><h2>지원 전략</h2><p>{content.applicationStrategy}</p></section><label className="consulting-report-release">공개 시각<input type="datetime-local" disabled={approved} value={releaseAt} onChange={event => setReleaseAt(event.target.value)} /></label><button className="consulting-v2-primary consulting-v2-wide" type="button" disabled={approved || !releaseAt || state.data.workflowState !== 'REPORT_REVIEW'} onClick={approve}>{approved ? '승인 완료' : '승인하고 공개 예약'}</button>{state.error ? <p role="status">{state.error}</p> : null}</article></main>;
}

export function ConsultingReportScreen({ binding }) {
  if (binding.userRole === 'tutor') return <CounselorReport binding={binding} />;
  if (binding.userRole === 'admin') return <AdminReport binding={binding} />;
  return <StudentReport binding={binding} />;
}
