import { expect, test } from '@playwright/test';
import { expectNoHorizontalOverflow, installApiMock } from './support/mock-api.mjs';

for (const viewport of [{ width: 320, height: 700 }, { width: 360, height: 640 }, { width: 390, height: 844 }, { width: 430, height: 932 }]) {
  test(`VP7 인증 구성과 복구 입력은 ${viewport.width}px에서 읽고 조작할 수 있다`, async ({ page }, testInfo) => {
    await page.setViewportSize(viewport);
    const api = await installApiMock(page);
    page.on('dialog', (dialog) => dialog.accept());
    await page.goto('/studycrack-mobile.html?screen=authLogin');
    await expect(page.getByRole('region', { name: '서비스 안내' })).toContainText('내 기록을 바탕으로');
    await expect(page.getByText('55.5%')).toHaveCount(0);
    const brand = await page.locator('.auth-brand-centered').boundingBox();
    const logo = await page.locator('.auth-brand-centered .auth-logo-wrap').boundingBox();
    expect(Math.abs(brand.x + brand.width / 2 - logo.x - logo.width / 2)).toBeLessThan(1);
    await expect(page.locator('.auth-unified-card .auth-signup-link')).toHaveCount(0);
    await expectNoHorizontalOverflow(page);
    await page.screenshot({ path: testInfo.outputPath(`login-${viewport.width}.png`), fullPage: true, animations: 'disabled' });
    const signupLink = page.locator('.auth-signup-link');
    await signupLink.scrollIntoViewIfNeeded();
    await expect(signupLink).toBeInViewport();
    await page.getByRole('button', { name: '서비스 소개 다시 보기' }).scrollIntoViewIfNeeded();
    await expect(page.getByRole('button', { name: '서비스 소개 다시 보기' })).toBeInViewport();
    if (viewport.height <= 700) await page.screenshot({ path: testInfo.outputPath(`login-footer-${viewport.width}.png`), fullPage: true, animations: 'disabled' });

    await page.getByRole('button', { name: '비밀번호 찾기' }).click();
    const dialog = page.getByRole('dialog', { name: '비밀번호 재설정' });
    await dialog.getByLabel('가입한 이메일').fill('student@example.com');
    await dialog.getByRole('button', { name: '인증 코드 받기' }).click();
    await expect(dialog.getByLabel('인증 코드', { exact: true })).toHaveValue('');
    await dialog.getByLabel('인증 코드', { exact: true }).fill('123456');
    await dialog.getByLabel('새 비밀번호', { exact: true }).fill('Secure-test123!');
    await dialog.getByLabel('새 비밀번호 확인', { exact: true }).fill('Different-test123!');
    await dialog.getByRole('button', { name: '비밀번호 변경 완료' }).click();
    expect(api.requests.filter(({ payload }) => payload.type === 'reset_password')).toHaveLength(0);
    await expect(dialog).toBeVisible();
    await expectNoHorizontalOverflow(page);
    await page.screenshot({ path: testInfo.outputPath(`recovery-${viewport.width}.png`), fullPage: true, animations: 'disabled' });
    await dialog.getByLabel('새 비밀번호 확인', { exact: true }).fill('Secure-test123!');
    await dialog.getByRole('button', { name: '비밀번호 변경 완료' }).click();
    await expect(dialog).toBeHidden();
    expect(api.requests.filter(({ payload }) => payload.type === 'reset_password')).toHaveLength(1);

    await page.goto('/studycrack-mobile.html?screen=authSignup');
    await expect(page.locator('.signup-progress [aria-current="step"]')).toContainText('약관');
    await page.getByRole('button', { name: '다음', exact: true }).click();
    await expect(page.locator('.signup-progress [aria-current="step"]')).toContainText('약관');
    for (const checkbox of await page.locator('[data-signup-term-required="true"]').all()) await checkbox.check();
    await expect(page.locator('[data-signup-term="marketing"]')).not.toBeChecked();
    await page.getByRole('button', { name: '다음', exact: true }).click();
    await expect(page.locator('.signup-progress [aria-current="step"]')).toContainText('본인 인증');
    await expect(page.locator('.signup-progress [data-complete="true"]')).toHaveCount(1);
    const birthdate = page.locator('[data-field="signupBirthdate"]');
    expect((await birthdate.boundingBox()).width).toBeGreaterThanOrEqual(155);
    await birthdate.fill('2008-12-31');
    await expect(birthdate).toHaveValue('2008-12-31');
    await page.screenshot({ path: testInfo.outputPath(`signup-phone-${viewport.width}.png`), fullPage: true, animations: 'disabled' });
    await page.getByRole('button', { name: '다음', exact: true }).click();
    await expect(page.locator('.signup-progress [aria-current="step"]')).toContainText('본인 인증');
    await page.getByRole('button', { name: '뒤로가기', exact: true }).click();
    await expect(page.locator('.signup-progress [aria-current="step"]')).toContainText('약관');
    for (const checkbox of await page.locator('[data-signup-term-required="true"]').all()) await expect(checkbox).toBeChecked();
    await expect(page.locator('[data-signup-term="marketing"]')).not.toBeChecked();
    await expectNoHorizontalOverflow(page);
    await page.screenshot({ path: testInfo.outputPath(`signup-terms-${viewport.width}.png`), fullPage: true, animations: 'disabled' });
    await page.getByRole('button', { name: '다음', exact: true }).click();
    await page.locator('[data-field="signupName"]').fill('테스트학생');
    await page.locator('[data-field="signupGender"]').selectOption('female');
    await page.locator('[data-field="signupPhone"]').fill('01012345678');
    await page.getByRole('button', { name: '다음', exact: true }).click();
    await expect(page.getByRole('alert')).toHaveText('전화번호 인증을 완료해주세요.');
    await page.getByRole('button', { name: 'SMS 인증번호 받기' }).click();
    await page.locator('[data-field="signupPhoneCode"]').fill('123456');
    await page.getByRole('button', { name: '확인', exact: true }).click();
    await expect(page.locator('.signup-verify-status')).toHaveText('전화번호 완료');
    await page.getByRole('button', { name: '다음', exact: true }).click();
    await expect(page.locator('.signup-progress [aria-current="step"]')).toContainText('이메일');
    await page.locator('[data-field="signupEmail"]').fill('student@example.com');
    await page.getByRole('button', { name: '다음', exact: true }).click();
    await expect(page.getByRole('alert')).toHaveText('이메일 인증을 완료해주세요.');
    await page.getByRole('button', { name: '이메일 인증번호 받기' }).click();
    await page.locator('[data-field="signupEmailCode"]').fill('123456');
    await page.getByRole('button', { name: '확인', exact: true }).click();
    await expect(page.locator('.signup-verify-status')).toHaveText('이메일 완료');
    if (viewport.width === 390) await page.screenshot({ path: testInfo.outputPath('signup-email-390.png'), fullPage: true, animations: 'disabled' });
    await page.getByRole('button', { name: '다음', exact: true }).click();
    await expect(page.locator('.signup-progress [aria-current="step"]')).toContainText('계정');
    await expect(page.locator('.signup-progress [data-complete="true"]')).toHaveCount(3);
    await expect(page.getByRole('button', { name: '회원가입 완료' })).toBeVisible();
    await expect(page.getByRole('button', { name: '회원가입 완료' })).toHaveClass(/btn-primary/);
    await expectNoHorizontalOverflow(page);
    if (viewport.width === 390) await page.screenshot({ path: testInfo.outputPath('signup-account-390.png'), fullPage: true, animations: 'disabled' });
  });
}
