import { expect, test } from '@playwright/test';
import { expectNoHorizontalOverflow, installApiMock, installAuthenticatedSession } from './support/mock-api.mjs';

test.use({ deviceScaleFactor: 1 });
for (const [width, height] of [[320, 700], [360, 800], [390, 844], [430, 932]]) {
  test(`MY·설정 메뉴와 계정 조작을 유지한다 (${width}px)`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height });
    page.on('dialog', dialog => dialog.accept());
    await installAuthenticatedSession(page);
    const email = 'long.account.address.for.presentation.test@example.com';
    const api = await installApiMock(page, { tier: 'standard', failOnceTypes: ['update_member_info'], userOverrides: { name: '긴이름을사용하는테스트학생', email, mbti: 'CSDR' } });
    const capture = name => page.screenshot({ path: testInfo.outputPath(`${name}-${width}.png`), fullPage: true, animations: 'disabled' });
    await page.goto('/studycrack-mobile.html?screen=my');
    await expect(page.locator('.my-insight-list > div')).toHaveCount(4);
    const cells = await page.locator('.my-insight-list > div').evaluateAll(nodes => nodes.map(node => { const r = node.getBoundingClientRect(); return { x: r.x, y: r.y }; }));
    expect(cells[0].y).toBe(cells[1].y);
    expect(cells[2].y).toBeGreaterThan(cells[0].y);
    await expectNoHorizontalOverflow(page);
    await capture('my');
    await page.locator('.my-profile-hero').click();
    const profile = page.getByRole('dialog', { name: '계정 및 구독 정보' });
    await expect(profile).toContainText(email);
    await expect(profile.locator('.profile-detail-row strong').filter({ hasText: email })).toHaveCSS('white-space', 'normal');
    await capture('profile');
    await profile.getByRole('button', { name: '닫기', exact: true }).click();
    await expect(page.locator('.my-profile-hero')).toBeFocused();
    await page.getByRole('button', { name: /약관 · 설정/ }).click();
    await expect(page.locator('[data-screen="settingsMain"]')).toBeVisible();
    await expect(page.locator('.my-menu-section h2')).toHaveText(['학습 알림', '계정 및 보안', '도움 및 지원', '로그인 상태']);
    await capture('settings');
    await page.getByRole('button', { name: /약관 보기 이용약관/ }).click();
    await page.getByRole('button', { name: /개인정보 처리방침 전문 보기/ }).click();
    await expect(page.getByRole('dialog')).toContainText('개인정보 처리방침');
    await page.keyboard.press('Escape');
    await page.goto('/studycrack-mobile.html?screen=settingsMain');
    await expect(page.locator('[data-screen="settingsMain"]')).toBeVisible();
    await page.getByRole('button', { name: /로그아웃 현재/ }).click();
    const logout = page.getByRole('dialog', { name: '로그아웃 확인' });
    await expect(logout).toBeVisible();
    await capture('logout');
    await logout.getByRole('button', { name: '취소' }).click();
    await expect.poll(() => page.evaluate(() => Boolean(sessionStorage.getItem('accessToken')))).toBe(true);
    await page.getByRole('button', { name: /알림 설정 플래너/ }).click();
    const planner = page.getByRole('switch', { name: '플래너 알림' });
    await expect(planner).toBeChecked();
    await planner.focus();
    await page.keyboard.press('Space');
    await expect.poll(() => api.requests.filter(({ payload }) => payload.type === 'update_member_info').length).toBe(1);
    await expect(planner).toBeChecked();
    await planner.click();
    await expect(planner).not.toBeChecked();
    await expect.poll(() => api.requests.filter(({ payload }) => payload.type === 'update_member_info').length).toBe(2);
    await capture('notifications');
    await page.goto('/studycrack-mobile.html?screen=accountInfo');
    const marketing = page.getByRole('switch', { name: '마케팅 수신 동의' });
    await marketing.click();
    await expect(marketing).toBeChecked();
    await expect.poll(() => api.requests.some(({ payload }) => payload.type === 'update_member_info' && payload.data?.marketingAgreed === true)).toBe(true);
    await page.getByRole('button', { name: '이름 변경', exact: true }).click();
    const edit = page.getByRole('dialog', { name: '이름 변경', exact: true });
    await expect(edit.getByLabel('새 이름')).toHaveCSS('font-size', '16px');
    await expect.poll(async () => (await edit.getByRole('button', { name: '닫기' }).boundingBox()).height).toBeGreaterThanOrEqual(44);
    await capture('name-edit');
    await edit.getByRole('button', { name: '취소' }).click();
    await page.locator('.account-withdraw-link').click();
    await expect(page.getByRole('dialog', { name: '회원탈퇴', exact: true }).getByLabel('현재 비밀번호')).toBeVisible();
    await capture('withdraw');
    await page.getByRole('dialog', { name: '회원탈퇴', exact: true }).getByRole('button', { name: '취소' }).click();
    expect(api.requests.some(({ payload }) => payload.type === 'delete_user')).toBe(false);
    await expectNoHorizontalOverflow(page);
  });
}
